config/routes.rb
Rails.application.routes.draw do
  get 'landing/index'
  root controller: :landing, action: :index

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_many :comments 
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :email, presence: true
  validates :comment, presence: true
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @article = Article.find(params[:article_id])
     @comments = Comment.new(article: @article)
  end

  def create
    @article = Article.find(params[:article_id])
     @comments = Comment.new(article: @article, comment: params[:comment][:comment], email: params[:comment][:email] )
     if @comments.save
     redirect_to root_path
   end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h2><%=@article.title %></h2>
<p><%=@article.content %></p>

<%= form_for [@article, @comments] do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %> <br />
  <%= f.label :comment %>
  <%= f.text_field :comment %><br />
  <%= f.submit 'Submit' %>
<% end %>

app/views/landing/index.html.erb
<ul>
  <% @articles.each do |article| %>
  <li>
    <h2><%= link_to article.title, new_article_comment_path(article.id) %><br /></h2>
    <%= article.content %>
  </li>
  <% if article.comments %>
       <% article.comments.each do |content| %>
           <h4>Comments</h4>
           <%= content.email %><br>
           <%= content.comment %>
       <% end %>
     <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFirst</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>